version: 0.2

phases:
  install:
    commands:
      - npm i
  test:
    commands:
      - npm test -- --watchAll=false
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: build
